# --- Packages --- #

library(DESeq2)

library(ggplot2)

# ---------------- #

# ----- DATA ----- #

# Count table generated by featureCounts
exp_data <- read.table(file = "featureCounts.txt",header = T)

# Information table about genes from NCTC8325 strain
gene_inf_data <- read.table(file = "/scripts/GeneSpecificInformation_NCTC8325.tsv", sep = "\t",header = T, na.strings = "", fill = T)

gene_inf_data <- gene_inf_data[-nrow(gene_inf_data),]

# Remove rows with NA values
gene_inf_data <- na.exclude(gene_inf_data)

# ---------------- #

# ---- DESeq2 ---- #

# Set experimental conditions
# Condition 1 : Control replicate / Condition 2 : Intracellular persister replicate
cond <- factor(rep(2:1,each = 3))

# Keep expression data
cnts <- exp_data[,7:ncol(exp_data)]

# Set row names as gene id from featureCounts
rownames(cnts) <- exp_data$Geneid

# Order DataFrame samples columns
cnts <- cnts[,order(colnames(cnts))]

# Clean rows names
rownames(cnts) <- vapply(rownames(cnts), function(x) substr(x, start = 6, stop = nchar(x)), character(1))

# Keep exp genes with informations available in information matrix
cnts <- cnts[which(rownames(cnts) %in% gene_inf_data$locus.tag),]

# Remove genes with no expression in all samples
cnts <- cnts[apply(cnts,1,sum) > 0,]

# Create DESeqDataSet from count table with experimental design
dds <- DESeqDataSetFromMatrix(cnts, DataFrame(cond), ~ cond)

# DESeq analyse
dds <- DESeq(dds)

res <- results(dds, independentFiltering = TRUE, pAdjustMethod = "BH")

# Create MA Plot
jpeg(filename = "MA-Plot_of_complete_RNA-seq_dataset.jpg")

plotMA(res, main = "MA-Plot of complete RNA-seq dataset", colNonSig = "black", colSig = "red", lty = 2)

dev.off()

# ---------------- #